### ISSUE TITLE
Can't install on Node 5 NVM 3.3.12

### ISSUE THREAD

**Issue by mcdonnelldean** [mcollina/autocannon#77] opened 2016-07-24 15:09 UTC
Just hangs,

- Hangs when installing via npm (any version)
- Hangs when installing locally to link (master branch)

I'm trying to get it working with Node 4 now via local, I'll ping when updated. (Although it looks to be hanging too)

**Comment by mcdonnelldean** [comment] 2016-07-24 15:22
Not working on 4.x either (npm 2.12.4). I've tried as far as 0.11.x

This is as far as I can get,

```sh
$ npm install
npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer requires a build toolchain, use it instead!
 
> native-hdr-histogram@0.3.2 preinstall /Users/mcdonnelldean/repos/autocannon/node_modules/native-hdr-histogram
> npm install node-pre-gyp

```

**Comment by mcdonnelldean** [comment] 2016-07-24 15:23
@mcollina @thekemkid Suggestions?

**Comment by mcdonnelldean** [comment] 2016-07-24 15:44
Seems https://github.com/mcollina/native-hdr-histogram is hanging, I tried to locally install and link, no dice either.

**Comment by thekemkid** [comment] 2016-07-24 15:50
Compatibility is node v4 and above just so you know. 

I think it has to do with npm v2, investigating

**Comment by mcdonnelldean** [comment] 2016-07-24 15:51
@thekemkid Yeah I assumed that. I've tried 4 and 5. No errors or anything, just hanging.

**Comment by thekemkid** [comment] 2016-07-24 15:55
Can you verify you can install https://github.com/mapbox/node-sqlite3?

**Comment by thekemkid** [comment] 2016-07-24 16:13
After chatting to @mcdonnelldean on skype, I cannot reproduce this right now, but I'll be investigating it more during the week.

**Comment by mcdonnelldean** [comment] 2016-07-24 16:18
For context, we have it working on 4.4.x. I'll test again with later versions once I am finished using it. It seems it may have been an npm brainfart but will confirm Monday.

**Comment by mcollina** [comment] 2016-07-24 22:30
Here is working fine/as expected. Maybe network/npm issues? Were you able to grab a npm log?

@thekemkid we should probably have some timeout in place to avoid these situations and fallback to build.

**Comment by davidmarkclements** [comment] 2016-07-25 16:38
working on OS X 10.11.1 - node v6.3.0, node installed with `n`

**Comment by mcollina** [comment] 2016-08-16 09:29
Closing, feel free to reopen if it happens again.

**Closed by mcollina** 2016-08-16 09:29 UTC
