### ISSUE TITLE
Extra stderr output when json is piped to file

### ISSUE THREAD

**Issue by bzoz** [mcollina/autocannon#81] opened 2016-08-08 10:45 UTC
Under Linux:
`autocannon -d -j example.com > stdout 2> stderr`

Result: JSON is stored in `stdout`. But default output (i.e. one with progress, results table etc.) is stored in `stderr`. This does not happen neither when output is not piped to file, nor when `-j` is not used.

**Comment by thekemkid** [comment] 2016-08-15 12:12
Should I remove the stderr output when json is being output?

**Comment by mcollina** [comment] 2016-08-16 09:14
Sorry, I'm missing a bit. What is the expected behavior you need @bzoz?

**Comment by bzoz** [comment] 2016-08-16 09:27
With `-j` provided I would expect to get only json and no other output.

**Comment by mcollina** [comment] 2016-08-16 09:36
We changed this recently because:

```
autocannon -j localhost:3000 > out
```

Will display a progress bar, and all the rest of the human readable output.
It's really handy when you are executing this in a Jenkins job, and you want to display both some human readable result for quick-consumption, and store the data somewhere.

You can remove the non-json output by passing the `-n` switch.
Maybe we should make that clearer in the docs.

**Comment by bzoz** [comment] 2016-08-16 09:44
This does not break anything for me, it is just a nit.

Anyhow - adding `-n` still produces summary (table with Latency, Req/Sec and Bytes/Sec) to the stderr.

**Comment by mcollina** [comment] 2016-08-16 11:14
Let me close this, and let's make sure `-n` does not print anything.

**Closed by mcollina** 2016-08-16 11:14 UTC
Labels: bug
